export const data = [
  {
    key: "1",
    text: "字节前端面试 1，",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: true,
  },
  {
    key: "2",
    text: "字节前端面试 1，",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: true,
  },
  {
    key: "3",
    text: "字节前端面试 1，",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: true,
  },
  {
    key: "4",
    text: "字节前端面试 1，面试没有结果啊啊啊，字节前端面试 1，面试没有结果啊啊啊字节前端面试 1，面试没有结果啊啊啊字节前端面试 1，面试没有结果啊啊啊字节前端面试 1，面试没有结果啊啊啊",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: true,
  },
  {
    key: "5",
    text: "字节前端面试 1，",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: false,
  },
  {
    key: "6",
    text: "字节前端面试 1，",
    cover: "",
    avatar: "",
    like_count: 100,
    isLiked: false,
  },
];
